version: "3"
services:
  react-app:
    build: ./
    container_name: react-app-container
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
