version: "3"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: stats-preview-card-component
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
